name: TestCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: sample
        run: |
          echo 'a'

      - name: error-step
        if: failure()
        run: |
          echo 'error'

      - name: success-step
        if: success()
        run: |
          echo 'success'
        