name: TestCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: sample
        run: |
          fejogeoge

      - name: index
        if: failure()
        run: |
          echo 'error'
        if: success()
        run: |
          echo 'success'
        